import type { Config } from "tailwindcss";

const hex = (token: string) =>
  `rgb(from var(${token}) r g b / <alpha-value>)`;

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        white: hex("--surface-card"),
        black: hex("--ink"),
        "surface-canvas": hex("--surface-canvas"),
        "surface-subtle": hex("--surface-subtle"),
        "surface-card": hex("--surface-card"),
        "surface-inset": hex("--surface-inset"),
        "surface-container": hex("--surface-container"),
        "text-primary": hex("--text-primary"),
        "text-secondary": hex("--text-secondary"),
        "text-muted": hex("--text-muted"),
        "text-faint": hex("--text-faint"),
        primary: hex("--primary"),
        "primary-hover": hex("--primary-hover"),
        "primary-dark": hex("--primary-dark"),
        "primary-light": hex("--primary-light"),
        "accent-coral": hex("--accent-coral"),
        "accent-terracotta": hex("--accent-terracotta"),
        "accent-blush": hex("--accent-blush"),
        "badge-warm-bg": hex("--badge-warm-bg"),
        "badge-warm-text": hex("--badge-warm-text"),
        "badge-warm-border": hex("--badge-warm-border"),
        "badge-sage-bg": hex("--badge-sage-bg"),
        "badge-sage-text": hex("--badge-sage-text"),
        "badge-sage-border": hex("--badge-sage-border"),
        "telemetry-active": hex("--telemetry-active"),
        "telemetry-warning": hex("--telemetry-warning"),
        "telemetry-error": hex("--telemetry-error"),
        "border-crisp": hex("--border-crisp"),
        "border-subtle": hex("--border-subtle"),
        "border-strong": hex("--border-strong"),
        "on-primary": hex("--on-primary"),
        brand: hex("--brand"),
        "brand-hover": hex("--brand-hover"),
        "brand-border": hex("--brand-border"),
        "on-brand": hex("--on-brand"),
        ink: hex("--ink"),
        "ink-banner": hex("--ink-banner"),
        "ink-hover": hex("--ink-hover"),
        "ink-elevated": hex("--ink-elevated"),
        "ink-soft": hex("--ink-soft"),
        "ink-muted": hex("--ink-muted"),
        "ink-faint": hex("--ink-faint"),
        "ink-hint": hex("--ink-hint"),
        "ink-quiet": hex("--ink-quiet"),
        hairline: hex("--hairline"),
        volt: hex("--volt"),
        "volt-hover": hex("--volt-hover"),
        "hero-canvas": hex("--hero-canvas"),
        "hero-glow": hex("--hero-glow"),
        "hero-line": hex("--hero-line"),
        "hero-field": hex("--hero-field"),
        "hero-frame": hex("--hero-frame"),
        "hero-rule": hex("--hero-rule"),
        "chrome-close": hex("--chrome-close"),
        "chrome-minimize": hex("--chrome-minimize"),
        "chrome-maximize": hex("--chrome-maximize"),
        "on-brand-ink": hex("--on-brand-ink"),
      },
      opacity: {
        4: "0.04",
        6: "0.06",
      },
      backgroundImage: {
        "brand-ink": "var(--brand-ink-gradient)",
      },
      boxShadow: {
        pill: "0 1px 2px rgb(from var(--shadow-ink) r g b / 0.04), 0 4px 16px rgb(from var(--shadow-ink) r g b / 0.04)",
        "pill-hover": "0 2px 8px rgb(from var(--shadow-ink) r g b / 0.06)",
        dropdown: "0 12px 40px rgb(from var(--shadow-ink) r g b / 0.1)",
        "mobile-cta": "0 4px 16px rgb(from var(--shadow-ink) r g b / 0.08)",
        field: "0 1px 2px rgb(from var(--shadow-ink) r g b / 0.04)",
        video: "0 -8px 40px rgb(from var(--shadow-ink) r g b / 0.08)",
        telemetry: "0 8px 30px rgb(from var(--shadow-warm) r g b / 0.06)",
      },
      spacing: {
        "space-2": "0.125rem",
        "space-4": "0.25rem",
        "space-8": "0.5rem",
        "space-12": "0.75rem",
        "space-16": "1rem",
        "space-20": "1.25rem",
        "space-24": "1.5rem",
        "space-32": "2rem",
        "space-40": "2.5rem",
        "space-48": "3rem",
        "space-64": "4rem",
        "space-80": "5rem",
        "space-96": "6rem",
        "gutter-desktop": "clamp(1rem, 4vw, 2rem)",
        "container-max": "1240px",
      },
      maxWidth: {
        "container-max": "1240px",
      },
      fontFamily: {
        sans: ["Outfit", "system-ui", "sans-serif"],
        display: ["Cormorant Garamond", "Georgia", "serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
        serif: ["Cormorant Garamond", "Georgia", "serif"],
      },
    },
  },
  plugins: [],
};

export default config;
